name: CoinSystem
main: com.davidout.CoinSystem.CoinAPI
author: David Out
version: 1.0
description: An easy to use coinsystem.
commands:
  coins:
    usage: /<command> <set, get, reset, add, remove> <player> <amount>
    description: see your coins amount or change someone coin amount.